[package]
name = "rust_am_client"
version = "0.1.0"
edition = "2021"

[dependencies]
bytestring = "1.3.1"
serde_json = "1.0.120"
hex = {version = "0.4.3"}
pico-args = {version = "0.5.0"}
rust_am_lib = { git = "https://github.com/ku-sldg/rust-am-lib.git" }